# -*- coding: utf-8 -*-
"""A106260073張雅雯109.03.13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZdlwPhMPQNYV8NkCVTt3rJCjZp6kDdkE
"""

#hello.py
print("Hello world!")

#zen.py
import this #python的哲學

#加分作業：用google colab寫作業，但程式附加檔名是.py，而不是.ipynb嗎？
#.ipynb是使用jupyter notebook編寫python程序時的文件，至於.py是指python編寫的文件。 對於.pynb開啟部分 沒辦法直接用Python來做開啟，而.py的檔案 可以直接用python做開啟