# -*- coding: utf-8 -*-
"""A106260073張雅雯_第二周.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rWBTpjjqddj-kKXXEK0PNl1Rfo4soSd9
"""

# input "03-19-2020"
# output "03-19-2020.csv"
#import requests
import pandas as pd

def get_covid_daily_data(input_date):
    csv_name = input_date + ".csv"
    github_url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/{}".format(csv_name)
    #response = requests.get(github_url)
    df = pd.read_csv(github_url)
    # df.head()
    # df.tail()
    df.to_csv(csv_name, index=False)

user_input = input("Please input a date(mm-dd-yyyy):")
get_covid_daily_data(user_input)

from datetime import date, timedelta

start_date = date(2020, 1, 22)
#time_delta = timedelta(57)
#end_date = start_date + time_delta
date_period = [start_date + timedelta(i) for i in range(58)]
data_dates = [i.strftime('%m-%d-%Y') for i in date_period]
for dt in data_dates:
    print("Downloading {}.csv...".format(dt))
    get_covid_daily_data(dt)

56_cannot_die = '五六不能亡'

cannot_56_die = '五六不能亡'
print(cannot_56_die)

cannot_die_56 = '五六不能亡'
print(cannot_die_56)

56_cannot_die = '五六不能亡'
print(56_cannot_die)

for = "For"

True = 1

print = 5566

movie_title = "Avengers: Endgame"
print(movie_title)

print = 5566
del print

movie_title = "Avengers: Endgame"
print(movie_title)

help(abs)

help(all)

my_object = 5566
print(my_object)

my_str = '5566'
print(my_str)

print(my_object**2)

print(my_str**2)

print(type(my_object))
print(type(my_str))

movie_title = "Avengers: Endgame"
movie_length = 181
movie_rating = 8.4

print(movie_title)
print(movie_length)
print(movie_rating)

print(type(movie_title))
print(type(movie_length))
print(type(movie_rating))

