# -*- coding: utf-8 -*-
"""week6-A106260073張雅雯

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pFij-OHU-nHc2GQVdzhFSc-1PQBysR9V
"""

print(False) #off
print(True)#on

#比較符號
print(7.7>8)
print(7.7>7)

print(type(7.7>8))
print(type(7.7>7))

print(7.7==8)
print(7.7!=8)

id_last_digit=5
id_last_digit%2==1 #看看是否為基數
id_last_digit%2==0 #看看是否為偶數

#反轉符號
print(not True)
print(not False)

print(not 7.7==8)
print(not 7.7!=8)

print(5566.00==5566)
print(type(5566.00))
print(type(5566))

5566 is 5566.00

5566 is not 5566.00

#布林運算符號
#not:非
#is 、is not:是否為相同的值
#and、or:交集與聯集

print(156< 120) #False
print(7.7>7) #True

print(156<120 and 7.7>7) #兩個都須符合

print(156<120 or 7.7>7) #有一個是對的就好

#資料轉換
city=input("請輸入所在的城市:")
weather=input("請輸入現在的天氣:")
tempc= input("請輸入現在的攝氏溫度:")
tempf=tempc*9/5+32 #除號不支援
print("我在{}，天氣{}，攝氏{}度，華氏{}度".format(city,weather,tempc,tempf))

print(tempc)
print(type(tempc)) #文字可以做加以及乘

tempc+"32"

tempc*5

#使用與資料類別相同名稱函數轉換
#int()：轉換為整數類別
#float()：轉換為浮點數類別
#str()：轉換為文字類別
#bool()：轉換為布林類別

print(int(tempc))
print(float(tempc))

print(type(int(tempc)))
print(type(float(tempc)))

city=input("請輸入所在的城市:")
weather=input("請輸入現在的天氣:")
tempc= input("請輸入現在的攝氏溫度:")
tempc=int(tempc)
tempf=tempc*9/5+32 
print("我在{}，天氣{}，攝氏{}度，華氏{}度".format(city,weather,tempc,tempf))

id_last_digit=input("請輸入身份證字號的尾數:")
id_last_digit=int(id_last_digit)
print(id_last_digit)
print(type(id_last_digit))
modulo=id_last_digit % 2
ans=modulo==1 #判斷結果
print(ans)

print(float('5566'))
print(int('5566'))

print(int(False))
print(int(False))

print(float(False))
print(float(True))

print(bool(0))
print(bool(1))
print(bool(5566))
print(bool(55.66))

#文字換布林
print(bool('True'))
print(bool('False'))

help(bin)

print(bin(0)) # 0 == 0 * 2^0
print(bin(1)) # 1 == 1 * 2^0
print(bin(2)) # 2 == 0 * 2^0 + 1 * 2^1
print(bin(3)) # 3 == 1 * 2^0 + 1 * 2^1
print(bin(4)) # 4 == 0 * 2^0 + 0 * 2^1 + 1 * 2^2
print(bin(5)) # 5 == 1 * 2^0 + 0 * 2^1 + 1 * 2^2
print(bin(6)) # 6 == 0 * 2^0 + 1 * 2^1 + 1 * 2^2
print(bin(7)) # 7 == 1 * 2^0 + 1 * 2^1 + 1 * 2^2

print(bin(False))
print(bin(True))

bin('A')

help(ord)

ord('A') #做間接地轉換

bin(ord('A'))

print(ord('!'))
print(ord('@'))
print(ord('#'))
print(ord('$'))





