# -*- coding: utf-8 -*-
"""week7_A106260073張雅雯

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u0qcVCrw6r98Fno9dSNiRo7Rfp765-mc
"""

last_id_digit=input("請輸入身分證字號的尾數:")
last_id_digit=int(last_id_digit)
remainder=last_id_digit %2
print("身分證字號尾數除以2的餘數為:{}".format(remainder))

last_id_digit=input("請輸入身分證字號的尾數:")
last_id_digit=int(last_id_digit)
remainder=last_id_digit %2
#條件判斷(begin)
if remainder==0: #bool 判斷結果
  ans="偶數"
else:
  ans="奇數"
  #條件判斷(end)
print("身分證字號尾數除以2的餘數為:{}，因此為{}".format(remainder,ans))

print(ord('A'))
print(chr(65)) #chr()意思是用一個整數做參數，返回對應的字符

print(ord('Z'))

print(ord('z'))

print(ord('a'))

print(chr(65))

#while 迴圈(begin)
i=65
while i<=90:#bool判斷結果
  print("character;{},Order;{},Binary{}".format(chr(i),i,bin(i)))
  i+=1
#while 迴圈(end)

member_ages=[18,20,22,25,32,42,65]
#資料篩選(begin)
list(filter(lambda x:x<=25 and x>=18, member_ages)) #bool判斷結果
#lambda是指匿名函數，需要一個函数，但是又不想費神去命名一個函数

#if expr:(expr被評估為true)
if True:
  print("判斷為真時印出")

#差別
#兩個差別在街True or False
#答案是否都印出來或者只印出一個
#if 只執行True不執行False

if True:#if:接在後面的是True or False,True會執行
  print(5566)
  print(1122)
print(7788)

if False:
  print(5566)
  print(1122)
print(7788)

movie_title=input('請輸入電影的名稱:')
movie_rating=input("請輸入電影的評等:")
movie_rating=float(movie_rating)

if movie_rating >7:
  print("{}的評分為{}分值得去看!".format(movie_title,movie_rating))
if movie_rating<=7:
  print("{}的評分為{}分不值得去看!".format(movie_title,movie_rating))

movie_rating>7

monthly_income=input("請輸入月薪:")
monthly_income=int(monthly_income)
saving_account=input("請輸入存款:")
saving_account=int(saving_account)
print(type(monthly_income))
print(type(saving_account))
ans=""
#條件判斷(begin)
if monthly_income >40000:
  ans='發信用卡'
if saving_account >500000:
  ans="發信用卡"
 #條件判斷(end)
print(ans)

monthly_income>40000

monthly_income=input("請輸入月薪:")
monthly_income=int(monthly_income)
saving_account=input("請輸入存款:")
saving_account=int(saving_account)
print(monthly_income >40000 and saving_account>500000)

monthly_income=input("請輸入月薪:")
monthly_income=int(monthly_income)
saving_account=input("請輸入存款:")
saving_account=int(saving_account)
print(monthly_income >40000 and saving_account>500000)

monthly_income=input("請輸入月薪:")
monthly_income=int(monthly_income)
saving_account=input("請輸入存款:")
saving_account=int(saving_account)
ans=""
if monthly_income >40000 or saving_account>500000:
  ans="發信用卡"
print(ans)

#else:判斷code block 會把反面那段完成
movie_title=input('請輸入電影的名稱:')
movie_rating=input("請輸入電影的評等:")
movie_rating=float(movie_rating)

if movie_rating >7:
  print("{}的評分為{}分值得去看!".format(movie_title,movie_rating))
else:
  print("{}的評分為{}分不值得去看!".format(movie_title,movie_rating))

user_int=input("請輸入一個正數:")
user_int=input("請輸入一個正整數:")
user_int=int(user_int)
if user_int%2==0: 
  ans="偶數"
else:
  ans="奇數"
print(ans)

user_int=input("請輸入一個正數:")
user_int=int(user_int)
if user_int%2==0: 
  ans="偶數"
if user_int%2==1:
  ans="奇數"
print(ans)

id_last_digit=input("請輸入身分證字號的尾數:")
print(type(id_last_digit))
id_last_digit=int(id_last_digit)
if id_last_digit%2==0:
  ans="星期二四六日領"
else:
  ans="星期一三五日領"
print(ans)

id_number=input("請輸入身分證字號:")

help(id)

id_number=input("請輸入身分證字號:")
id_last_digit=id_number[-1]
id_last_digit=int(id_last_digit)
if id_last_digit%2==0:
  ans="星期二四六日領"
else:
  ans="星期一三五日領"
print(ans)

id_number=input("請輸入身分證字號:")
id_second_digit=id_number[1]
print(id_second_digit)
if id_second_digit=='1':
  gender='Male'
else:
  gender='Female'
print(gender)

movie_title=input('請輸入電影的名稱:')
movie_rating=input("請輸入電影的評等:")
movie_rating=float(movie_rating)

if movie_rating>7:
  print("去電影院看{}".format(movie_title))
elif movie_rating>6:
    print("去家裡看{}".format(movie_title))
else:
  print("不要看{}".format(movie_title))

height=input("請輸入身高:")
height=int(height)
kilo=input("請輸入體重:")
kilo=float(kilo)
bmi=kilo/(height*0.01)**2
if bmi>30:
  ans="obese"
elif bmi>25:
  ans="overweight"
elif bmi>18.5:
  ans="Normal range"
else:
  ans="underweight"
print(ans)

































